---
nav:
  -
    icon: home
    path: homepage
    title: Home
  -
    icon: wrench
    path: project
    title: Projects
  -
    icon: file
    path: product
    title: Products
  -
    icon: user
    path: owners
    title: Owners
  -
    icon: globe
    path: /csw
    title: CSW
right:
  -
    icon: github
    path: https://github.com/arcticlcc/metadata-catalog
    title: GitHub
