MetaCat\Entity\Product:
    type: entity
    table: product
    readOnly: true
    manyToOne:
      project:
        targetEntity: Project
        inversedBy: products
        joinColumn:
          name: projectid
          referencedColumnName: projectid
          onDelete: SET NULL
    id:
        productid:
            type: guid
            generator: { strategy: UUID }
    fields:
        projectid:
            type: guid
            nullable: true
        json:
            type: jsonb
        xml:
            type: text
            nullable: true
        html:
            type: text
            nullable: true
            
